### ISSUE TITLE
This content show up after installed and try to play something on Tidal

### ISSUE THREAD

**Issue by CX838** [1nikolas/tidal-lyrics#16]
Hi There. I am using Macbook Pro with M1 here.
I installed the file completely fine and gave the permission of access.
 When I play something on Tidal then it shows me this.
 I am so sorry. I am a totally tech dumb dumb. This is as far as I can go.
Can you tell me what should i fix?
Thanks for your time.

Uncaught Exception:
SyntaxError: Unexpected token 
in JSON at position 7
at JSON.parse (<anonymous>)
at Request._callback (/Applications/tidal-lyrics.app/Contents/Resources/app/src/index.js:377:34)
at Request.self.callback (/Applications/tidal-lyrics.app/Contents/Resources/app/node_modules/request/request.js:185:22)
at Request.emit (events.js:310:20)
at Request.<anonymous> (/Applications/tidal-lyrics.app/Contents/Resources/app/node_modules/request/request.js:1154:10)
at Request.emit (events.js:310:20)

**Comment by 1nikolas** [comment]
Hello.
Can you provide the log file after the error has occurred? You can open it from the about menu and then copy paste it here. If you can't access the about menu, it's located at `~/Library/Logs/tidal-lyrics` (`~` is your user folder; the Library folder is hidden by default, to temporarily unhide it you can press `Command + Shift + . (full stop/period)`). After going in that folder, you should see an `app.txt` file. Just keep in mind that the log resets every time you open the app.

If you have any trouble with all that please let me know.

**Comment by CX838** [comment]
[2021JL26Tidal-lyrics-testrun.log](https://github.com/1nikolas/tidal-lyrics/files/6876850/2021JL26Tidal-lyrics-testrun.log)


I shut it down earlier then it works for a little while this time. then it went back crazy again.
and at the same time i am also playing offline mode on my phone with musixmatch running. 
so there was only 1 song doesn't have lyric file.
i am trying with japanese songs so the code is more clear for you to read.

btw. i found that i pressed "Toggle Full Screen" then the text changed to "Tidal is not running"

is there anything else you like me to try with??? just ask

**Comment by 1nikolas** [comment]
Okay. About the fullscreen thing I don't think there is any workaround. The program takes the song data from the "Window Title" (which you don't really see on MacOS but it exists) and I suppose the fullscreen on Mac doesn't have a title (on Windows it works fine). I'll work on a better error handling right now (to deal with the initial problem) and then see what's going on with the fullscreen on Mac. Thanks for the log

**Comment by 1nikolas** [comment]
I think I fixed the problem but my MacOS Virtual Machine is not working right now so I can't get any MacOS builds. I'll send you a test build here to test when I manage to fix it

**Comment by 1nikolas** [comment]
Hello, sorry for the delay.
Here is the test build I was talking about. Please test it and see if the problem still persists. I don't know what exactly is causing the problem as I didn't manage to reproduce it, but it should at least give an error instead of crashing. Thanks

https://www.dropbox.com/s/nsu0wywmri54ab8/tidal-lyrics%20testbuild.dmg?dl=0
